parameters:
#    flowcode_news.example.class: Flowcode\NewsBundle\Example

services:

    news.form.type.post:
        class: Flowcode\NewsBundle\Form\PostType
        arguments: ['@amulen.classification.category']
        tags:
            - { name: form.type, alias: post_type }