parameters:
#    flowcode_news.example.class: Flowcode\NewsBundle\Example

services:

    news.form.type.post:
        class: Flowcode\NewsBundle\Form\PostType
        arguments: ['@amulen.classification.category']
        tags:
            - { name: form.type, alias: post_type }

    amulen.news.showmenu_eventsubscriber:
        class: Flowcode\NewsBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }

    amulen.news.listplugins_eventsubscriber:
        class: Flowcode\NewsBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }
